### ISSUE TITLE
camera、selectコンポーネントについて

### ISSUE THREAD

**Issue by Nobu19800** [Ruchi12377/RT#4]
camera、selectというRTCで、cameraコンポーネントで画像データを一旦保存して、画像ファイルのパスを送信後に、selectコンポーネントでファイルを開くという事をしていますが、データポートで直接画像データをやり取りしたほうが他のRTCとも接続しやすくなると思いました。
PythonでCameraImage型とOpenCVの画像データの変換方法が分からない場合は以下のソースコードを参考にしてください。

 - https://github.com/Nobu19800/testOpenRTM-aist/blob/57c91e260c6376574b5f1cc893aced4cf2d30adf/testOutPortpy/testOutPortpy.py
 - https://github.com/Nobu19800/testOpenRTM-aist/blob/57c91e260c6376574b5f1cc893aced4cf2d30adf/testInPortpy/testInPortpy.py

**Comment by ghost** [comment]
ご指摘ありがとうございます。
直接ポートで画像データをやりとりできるよう改善しました。
[改善したコミット](https://github.com/Ruchi12377/RT/commit/028fac96d1ae6daee9b69cfebc3138495ebea3f5)
ご確認よろしくお願いします。

**Comment by Nobu19800** [comment]
確認しました。修正していただいてありがとうございます。
